AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  ApplicationName:
    Type: String
    Description: The application name that is being deployed
  EnvironmentName:
    Type: String
    Description: The environment in which the stack will be deployed
  HostedZoneName:
    Type: String
    Description: The name of the hosted zone where DNS should be placed
  DomainName:
    Type: String
    Description: The domain name the application will be behind


Resources:
  Data:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/data.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        EnvironmentName: !Ref EnvironmentName

  Auth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/auth.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        EnvironmentName: !Ref EnvironmentName

  Cert:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/cert.yml
      Parameters:
        HostedZoneName: !Ref HostedZoneName
        DomainName: !Ref DomainName

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/api.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        EnvironmentName: !Ref EnvironmentName
        HostedZoneName: !Ref HostedZoneName
        DomainName: !Ref DomainName
        CertificateArn: !GetAtt Cert.Outputs.CertificateArn
        TableArn: !GetAtt Data.Outputs.TableArn
        TableName: !GetAtt Data.Outputs.TableName


Outputs:
  ApiEndpoint:
    Value: !GetAtt Api.Outputs.ApiEndpoint
    Description: API Gateway endpoint URL for the API
