AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  ApplicationName:
    Type: String
    Description: The application name that is being deployed
  EnvironmentName:
    Type: String
    Description: The environment in which the stack will be deployed
  Version:
    Type: String
    Description: The version of the application being deployed
  HostedZoneName:
    Type: String
    Description: The name of the hosted zone where DNS should be placed
  DomainName:
    Type: String
    Description: The domain name the application will be behind


Resources:
  Data:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/data.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        EnvironmentName: !Ref EnvironmentName

  Auth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/auth.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        EnvironmentName: !Ref EnvironmentName
        DomainName: !Ref DomainName

  Cert:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/cert.yml
      Parameters:
        HostedZoneName: !Ref HostedZoneName
        DomainName: !Ref DomainName

  Frontend:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/frontend.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        EnvironmentName: !Ref EnvironmentName
        Version: !Ref Version
        HostedZoneName: !Ref HostedZoneName
        CertificateArn: !GetAtt Cert.Outputs.CertificateArn
        DomainName: !Ref DomainName
        ApiEndpoint: !GetAtt Api.Outputs.ApiEndpoint
        AuthAppClientId: !GetAtt Auth.Outputs.AppClientId
        AuthBaseUrl: !GetAtt Auth.Outputs.AuthBaseUrl

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/api.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        EnvironmentName: !Ref EnvironmentName
        Version: !Ref Version
        HostedZoneName: !Ref HostedZoneName
        DomainName: !Ref DomainName
        CertificateArn: !GetAtt Cert.Outputs.CertificateArn
        TableArn: !GetAtt Data.Outputs.TableArn
        TableName: !GetAtt Data.Outputs.TableName
        AuthUserPoolId: !GetAtt Auth.Outputs.UserPoolId
        AuthAppClientId: !GetAtt Auth.Outputs.AppClientId


Outputs:
  ApiEndpoint:
    Value: !GetAtt Api.Outputs.ApiEndpoint
    Description: API Gateway endpoint URL for the API
  AppEndpoint:
    Value: !GetAtt Frontend.Outputs.AppEndpoint
    Description: App endpoint URL for the frontend
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt Auth.Outputs.UserPoolId
  AppClientId:
    Description: Cognito App Client ID
    Value: !GetAtt Auth.Outputs.AppClientId
