name: build
run-name: 'build: ${{ github.event.head_commit.message }}'

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./scripts/utils/build.sh
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: result
